language: go
go:
  - 1.6
  - tip
install:
  - go get github.com/gorilla/mux
  - go get github.com/streadway/amqp
  - go get github.com/garyburd/redigo/redis
services:
  - rabbitmq
  - redis-server
env:
  - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/
  - REDIS_URL=redis://127.0.0.1:6380/0
script: go test ./...
notifications:
  email:
    recipients:
      - devs@eventials.com
    on_success: never
    on_failure: always
