language: go
go:
  - 1.6
  - tip
install:
  - go get github.com/gorilla/mux
  - go get github.com/streadway/amqp
  - go get github.com/getsentry/raven-go
services:
  - rabbitmq
env:
  - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/
script: go test ./...
notifications:
  email:
    recipients:
      - devs@eventials.com
    on_success: never
    on_failure: always
