web:
  build: .
  working_dir: /go/src/github.com/eventials/frodo
  command: dockerize -wait tcp://broker:5672 -timeout 60s go run server.go
  links:
   - broker
   - cache
  ports:
   - "3000:3000"
  environment:
    FRODO_CORS: 'true'
    FRODO_BROKER: amqp://guest:guest@broker:5672/
    FRODO_CACHE: cache:6379
  volumes:
   - .:/go/src/github.com/eventials/frodo
  hostname: frodo
cache:
  image: redis:3.0
broker:
  image: rabbitmq:3.6-management
  ports:
   - "15672:15672"
